VERSION: 2
_BASE_: "centermask_V_39_eSE_FPN_ms_3x.yaml"
TEST:
  KEYPOINT_OKS_SIGMAS: []
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  DEVICE: "cuda"
  FCOS:
    NUM_CLASSES: 3
  RETINANET:
    NUM_CLASSES: 3
  RPN:
    BATCH_SIZE_PER_IMAGE: 256
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 128
    NUM_CLASSES: 3
  SEM_SEG_HEAD:
    NUM_CLASSES: 3
  ROI_KEYPOINT_HEAD:
    NUM_KEYPOINTS: 17
DATASETS:
  TRAIN: (["can_train"])
  TEST: (["can_val"])
SOLVER:
  CHECKPOINT_PERIOD: 100
  IMS_PER_BATCH: 1
  BASE_LR: 0.01  # Note that RetinaNet uses a different default learning rate
  STEPS: (6, 8)
  MAX_ITER: 10
